  runtime: java17
  env: standard
  instance_class: F2

  entrypoint: "java -jar target/project-1.0.war"

  env_variables:
    BUCKET_NAME: "milkteacloud"

  handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
